In [77]:
import numpy as np
arr = np.array([1,3,5,9])
print(arr)

[1 3 5 9]


In [78]:
arr1 = np.arange(7)
print("Using np.arrange(7):", arr1)
arr2 = np.arange(1, 8, 2)
print("Using np.arrange(1,8,2):", arr2)

Using np.arrange(7): [0 1 2 3 4 5 6]
Using np.arrange(1,8,2): [1 3 5 7]


In [79]:
arr = np.random.rand(4)
print(arr)

[0.83113468 0.95126444 0.75899622 0.83905222]


In [80]:
arr = np.array([[[2,4,9,4],
                 [1,2,3,4],
                 [5,7,4,3]],
                [[1,2,45,8],
                 [24,89,23,85],
                 [78,6,47,21]]])
print(arr)

[[[ 2  4  9  4]
  [ 1  2  3  4]
  [ 5  7  4  3]]

 [[ 1  2 45  8]
  [24 89 23 85]
  [78  6 47 21]]]


In [81]:
arr1 = np.random.rand(3,3)
print("2-D Array")
print(arr1)

arr2 = np.random.rand(3,3,2)
print("3-D Array")
print(arr2)

2-D Array
[[0.07866481 0.78689611 0.65883711]
 [0.69930387 0.67172062 0.93196183]
 [0.58645668 0.07753901 0.79536642]]
3-D Array
[[[0.67359083 0.658003  ]
  [0.77236613 0.78660389]
  [0.41682126 0.32106921]]

 [[0.14738001 0.82424559]
  [0.35514012 0.06479786]
  [0.25273538 0.11943018]]

 [[0.78004267 0.7682351 ]
  [0.34488541 0.06032322]
  [0.27335705 0.47614548]]]


In [82]:
a = np.array(42)
b = np.array([1,3,4,7])
c = np.array([[1,3,4], [5,7,3]])
d = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [2,7,3]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

arr = np.array([2,4,5,7], ndmin=5)
print(arr)
print("Number of dimension: ", arr.ndim)

0
1
2
3
[[[[[2 4 5 7]]]]]
Number of dimension:  5


In [83]:
arr = np.array([[1,3,4], [5,7,3]])
print(arr.shape)

(2, 3)


In [84]:
arr = np.array([1,2,3])
for x in arr:
    print(x)

arr = np.array([[1,2,3],[4,5,6]])
for x in arr:
    for y in x:
        print(y, end="\t")

print("\n")
for x in arr:
    print(x)

1
2
3
1	2	3	4	5	6	

[1 2 3]
[4 5 6]


In [85]:
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [2,7,3]]])

for x in arr:
    print(x)

for i in arr:
    for j in i:
        for k in j:
            print(k, end=" ")

[[1 2 3]
 [4 5 6]]
[[7 8 9]
 [2 7 3]]
1 2 3 4 5 6 7 8 9 2 7 3 

In [86]:
arr = np.array([[1,2,3,4],[5,6,7,8]])

for x in np.nditer(arr[:, ::2]):
    print(x, end=" ")



1 3 5 7 

In [87]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9], [2,7,3]])

sec_row = arr[1,:]
print("Second Row:", sec_row)

third_col = arr[:,2]
print("Third col:", third_col)

Second Row: [4 5 6]
Third col: [3 6 9 3]


## ASSIGNMENT

In [88]:
# ZIP
a = [1,2,3]
b = ["a", "b", "c"]

my_iter = zip(a,b)
for elem in my_iter:
    print(elem)

(1, 'a')
(2, 'b')
(3, 'c')


In [89]:
import pickle

# Mount your google drive
# from google.colab import drive
#drive.mount('/content/drive')

# Serialize an object to a file on google drive
# my_obj = {"a":1, "b":2, "c":3}

# with open("/content/drive/My Drive/my_obj.pkl", "wb") as pickle_file:
    # pickle.dump(my_obj, pickle_file)

In [90]:
!ls -al

total 20
drwxr-xr-x 1 root root 4096 Oct 31 05:59 .
drwxr-xr-x 1 root root 4096 Oct 31 04:39 ..
drwxr-xr-x 4 root root 4096 Oct 27 13:22 .config
drwx------ 6 root root 4096 Oct 31 05:59 drive
drwxr-xr-x 1 root root 4096 Oct 27 13:22 sample_data


In [91]:
import pickle

with open("/content/drive/My Drive/my_obj.pkl", "rb") as pickle_file:
    my_obj = pickle.load(pickle_file)
    print(my_obj)

{'a': 1, 'b': 2, 'c': 3}


In [92]:
import collections

def bubble_sort(collection):
    for i in range(len(collection) - 1):
        for j in range(len(collection) - i - 1):
            if(collection[j] > collection[j+1]):
                collection[j], collection[j+1] = collection[j+1], collection[j]

    return collection

my_list = [5, 3, 2, 1, 4]
sorted_list = bubble_sort(my_list)
print(sorted_list)

[1, 2, 3, 4, 5]


In [93]:
# stack using deque
from collections import deque

st = deque()

st.append('a')
st.append('b')
st.append('c')
print(st)
print(st.pop())
print(st.pop())
print(st.pop())

deque(['a', 'b', 'c'])
c
b
a


In [94]:
# merge sort
import collections

def merge_sort(collection):
    if len(collection) <= 1:
        return collection

    mid = len(collection) // 2
    left = merge_sort(collection[:mid])
    right = merge_sort(collection[mid:])

    return merge(left, right)

def merge(left, right):
    res = collections.deque()
    i = 0
    j = 0
    while i < len(left) and j < len(right):
        if left[i]  <= right[j]:
            res.append(left[i])
            i += 1
        else:
            res.append(right[j])
            j += 1

    while i < len(left):
        res.append(left[i])
        i += 1

    while j < len(right):
        res.append(right[j])
        j += 1

    return list(res)

collection = [1,3,3,4,6,6,5,2,2,4,2,7,8,1,4,3]
sorted_collection = merge_sort(collection)
print(sorted_collection)

[1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 6, 6, 7, 8]


In [95]:
# selection sort
import collections

def selection_sort(collection):
    for i in range(len(collection) - 1):
        min_index = i
        for j in range(i+1, len(collection)):
            if collection[j] < collection[min_index]:
                min_index = j

        collection[i], collection[min_index] = collection[min_index], collection[i]

    return collection

collection = [1,3,34,4,6,76725,452,512,2,4,12,87,85,1,434,3]
sorted_collection = merge_sort(collection)
print(sorted_collection)

[1, 1, 2, 3, 3, 4, 4, 6, 12, 34, 85, 87, 434, 452, 512, 76725]


In [96]:
# insertion sort
import collections

def insertion_sort(collection):
    for i in range(1, len(collection)):
        curr = collection[i]
        j = i-1
        while j >= 0 and collection[j] > curr:
            collection[j+1] = collection[j]
            j -= 1
        collection[j+1] = curr

    return collection

collection = [1,3,34,4,6,76725,452,512,2,4,12,87,85,1,434,3]
sorted_collection = merge_sort(collection)
print(sorted_collection)

[1, 1, 2, 3, 3, 4, 4, 6, 12, 34, 85, 87, 434, 452, 512, 76725]


In [98]:
# Binary Search Tree

class Node:
    def __init__(self, key):
        self.key = key
        self.left = None
        self.right = None

def inorder(root):
    if root is not None:
        inorder(root.left)
        print(str(root.key) + "->", end=' ')
        inorder(root.right)

def insert(node, key):
    if node is None:
        return Node(key)

    if key < node.key:
        node.left = insert(node.left, key)
    else:
        node.right = insert(node.right, key)

    return node

def minValueNode(node):
    current = node

    while(current.left is not None):
        current = current.left

    return current

def deleteNode(root, key):
    if root is None:
        return root

    if key < root.key:
        root.left = deleteNode(root.left, key)
    elif(key > root.key):
        root.right = deleteNode(root.right, key)
    else:
        if root.left is None:
            temp = root.right
            root = None
            return temp

        elif root.right is None:
            temp = root.left
            root = None
            return temp

        temp = minValueNode(root.right)
        root.key = temp.key
        root.right = deleteNode(root.right, temp.key)

    return root

root = None
root = insert(root, 8)
root = insert(root, 3)
root = insert(root, 1)
root = insert(root, 6)
root = insert(root, 7)
root = insert(root, 10)
root = insert(root, 14)
root = insert(root, 4)

print("Inorder traversal: ", end=' ')
inorder(root)

print("\nDelete 10")
root = deleteNode(root, 10)
print("Inorder traversal: ", end=' ')
inorder(root)

Inorder traversal:  1-> 3-> 4-> 6-> 7-> 8-> 10-> 14-> 
Delete 10
Inorder traversal:  1-> 3-> 4-> 6-> 7-> 8-> 14-> 

In [99]:
list1 = [1,2,3,4,5,6]
list1.append(0)
print(list1)

[1, 2, 3, 4, 5, 6, 0]
